import localFont from "next/font/local";
import "./globals.css";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner"; // Import Toaster

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextAuthSessionProvider>
          <div className="mx-6 md:mx-16">
            {children}
            <Toaster /> {/* Add Toaster here */}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}